sudo: required
services:
  - docker

before_install:
  - docker build -t bjowczarek/docker-react -f Dockerfile.dev .

script:
  - docker run bjowczarek/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-simple-app"
  env: "DockerSimpleApp-env"
  bucket_name: "elasticbeanstalk-eu-west-2-922687003324"
  bucket_path: "docker-simple-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
